[package]
name = "amaze"
description = "A maze generator"
keywords = ["maze", "maze-generator"]
categories = ["game-development", "simulation"]
authors = ["Markus Mayer <widemeadows@gmail.com>"]
homepage = "https://github.com/sunsided/amaze-rs"
repository = "https://github.com/sunsided/amaze-rs"
license = "EUPL-1.2 OR MIT OR Apache-2.0"
readme = "../README.md"
version = "0.1.1"
edition = "2021"

[features]
default = ["renderers"]
renderers = ["unicode-renderer", "pgm-renderer"]
unicode-renderer = []
pgm-renderer = []

[dependencies]
rand = "^0.8.5"

[dev-dependencies]
indoc = "2.0.5"
